name: Build Android and iOS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    workflow_dispatch:

jobs:
    install-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install --lockfile-version 1
            - name: Run tests
              run: |
                  npm test
    build-android:
        needs: install-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install --lockfile-version 1
            - name: Build Android Release
              run: |
                  NODE_OPTIONS=--openssl-legacy-provider npm run build-android
            - name: Upload Artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: apks.zip
                  path: android/app/build/outputs/apk/debug/
    build-ios:
        needs: install-and-test
        runs-on: [self-hosted, macos]
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install
            - name: Install pod dependencies
              run: |
                  cd ios && pod install
            - name: Build app
              run: |
                  xcodebuild -workspace myapp.xcworkspace -scheme myapp archive -archivePath myapp.xcarchive -allowProvisioningUpdates
                  xcodebuild -exportArchive -archivePath ./myapp.xcarchive -exportPath . -exportOptionsPlist myapp/Info.plist
                  mv myapp.ipa ../myapp.ipa
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: myapp.ipa
                  path: ios/build/
