name: Build Android and iOS
on:
    push:
        branches:
            - master
jobs:
    install-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install --lockfile-version 1
            - name: Run tests
              run: |
                  npm test
    build-android:
        needs: install-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install --lockfile-version 1
            - name: Build Android Release
              run: |
                  NODE_OPTIONS=--openssl-legacy-provider npm run build-android
            - name: Upload Artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: apks.zip
                  path: android/app/build/outputs/apk/debug/
