name: Build Android and iOS
on:
    push:
        branches:
            - master
jobs:
    install-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install --lockfile-version 1
            - name: Run tests
              run: |
                  npm test
    build-android:
        needs: install-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install --lockfile-version 1
            - name: Build Android Release
              run: |
                  NODE_OPTIONS=--openssl-legacy-provider npm run build-android
            - name: Upload Artifact (x86)
              uses: actions/upload-artifact@v1
              with:
                  name: app-x86-debug.apk
                  path: android/app/build/outputs/apk/debug/
            - name: Upload Artifact (x64)
              uses: actions/upload-artifact@v1
              with:
                  name: app-x86_64-debug.apk
                  path: android/app/build/outputs/apk/debug/
            - name: Upload Artifact (armeabi)
              uses: actions/upload-artifact@v1
              with:
                  name: app-armeabi-v7a-debug.apk
                  path: android/app/build/outputs/apk/debug/
            - name: Upload Artifact (arm64)
              uses: actions/upload-artifact@v1
              with:
                  name: app-arm64-v8a-debug.apk
                  path: android/app/build/outputs/apk/debug/
